### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by bakpakin** [bakpakin/janet#9]
Dst is not a descriptive, meaningful, or memorable name that unfortunately is also short for Day Savings Time.

Some  ideas:
- mite, or mitelang 
- dust, similar to dst, a project with this name already exists
- Tupper, short for TUPle PRocessing instead of lisp processing

Very open to new ideas.

**Comment by Gavlooth** [comment]
All these names are cute, but I dont think are good "marketing".
How about something like S-exscript. This will draw attention and is descriptive (s-expressions & scripting and subconsciously  sex :P ), also it doesnt ring "not a lisp" etc etc .
Writing things like "Is not a lisp" etc etc , gives a negative emotion to lisp 
lovers (As a clojure lover, i know, i feel it), while just saying  sexp is more or less lisp inside our heads. 
I think marketing-wise "A scripting language that combines the powerful scripting mechanism of lua 
and the expressiveness of clojure" or "sexp and enhanced data structures". Here i avoided the term lisp because syntax is more clojure-wise and
scripting is a large vacuum for clojurers, so i assume that someone from clojure will be attracted to the familiarity.
Of course none of these have to do with the language implementation, but they dont lie either, is just good politics  3:) 
the name "S-exscript" is just a suggestion from the top of my head.

**Comment by bakpakin** [comment]
I guess I will think about this more. Dst was originally short for Data Structures, and I think it is important to market the capabilities, namely a clojure like language that is useful as a lightweight but capable scripting language, with a few useful core data structures. That said, my goals for dst are a bit loftier than a scripting language and I think there are a number of interesting features in the language that are not fully fleshed out or proven, (fibers, extension with C, saving and loading the compiled bytecode, etc.) Hence, I would rather not include 'Script' in the name.

**Comment by Gavlooth** [comment]
Yes i noticed the assembler, and extension with C. And the fiber type, (which i know nothing about) 
 It would be also good if the name had some googlespace area (clojure had 0 hits but thats rare).

**Comment by bakpakin** [comment]
Alternative names for the same kind of thing are green threads and coroutines (although fibers will provide a little bit more that traditional coroutine implementations), or for the lisp community a form of safer and faster (but more limited) continuation.

**Comment by Gavlooth** [comment]
Ok a compined work might serve
Something like
(str (or data sexp)  (or proc magi))

**Comment by Gavlooth** [comment]
Datamuse sexpmuse  or one compined with one of the duties of knowledge seems appealing to me 
https://en.wikipedia.org/wiki/List_of_knowledge_deities . I will keep bombing here probably :P

**Comment by Gavlooth** [comment]
How about Sexplojion or Sexplojure :P

**Comment by bakpakin** [comment]
Nah, I think we should pass on the sex names. I was thinking dstructure, as a pun on destructuring, data structures, and dst. Thoughts?

**Comment by Gavlooth** [comment]
Like D-structure?  It's good, but i feel  some uniqueness from how it sounds is missing. Remember also the google space.

**Comment by Gavlooth** [comment]
Have you decided on the name ? 
I have been reading about Clojure data structures a little, lately. 
It turns that Clojure lists are essentially tuples, since they are "persistence lists" so your implementation is in par with Clojure. Also Clojure doenst have immutable arrays but implements rrb trees with 32 element nodes.

**Comment by bakpakin** [comment]
I have not yet decided on a name. I figured there was no rush. I have been thinking about it though.

Yes, a lot of the immutable structure are similar to clojure’s in interface, though not implementation. Clojure seems to prefer trees instead of more straight forward array based structures. In implementing the core library, I find myself using the mutable structures a bit like clojures transients.
